// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://skqvsioavtgbbttpwrmh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNrcXZzaW9hdnRnYmJ0dHB3cm1oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxOTczNDMsImV4cCI6MjA2NDc3MzM0M30.I4_fERwrCHvgv6PI5iudmxregE7vEFks4h_M7aRQByo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);