// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://whlrsycglgecbgcidhod.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndobHJzeWNnbGdlY2JnY2lkaG9kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMDI1ODksImV4cCI6MjA2NTg3ODU4OX0.Ap6Dex0wMAMIxRPF_MXSFJhl035ksj76rG0lZbAvq_M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);